version: "3"
services:
    db:
        build:
          context: ./db
        environment:
          POSTGRES_PASSWORD: example
          POSTGRES_USERNAME: postgres
          POSTGRES_DATABASE: project_management
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - pg-datafolderv2:/var/lib/postgresql/data
    frontend:
        build:
          context: ./frontend
        volumes:
          - /app/node_modules
          - ./frontend:/app
    api:
        build:
          context: ./node_graphQL_server_with_prisma
        depends_on:
          - db
        # command: >
        #   bash "npx prisma migrate dev"
    nginx:
        build:
            context: ./nginx
        volumes:
          - ./nginx/templates:/etc/nginx/templates
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        ports:
          - "80:80"
        depends_on:
          - api
          - frontend
volumes:
    pg-datafolderv2:
    