version: "3"
services:
    db:
        build:
          context: ./db
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
          POSTGRES_DB: project_management
          POSTGRES_PASSWORD: 1234
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - pg-datafolderv8:/var/lib/postgresql/data
    frontend:
        build:
          context: ./frontend
        volumes:
          - /app/node_modules
          - ./frontend:/app
          # - ./frontend/build:/var/www/html
          # - ./deploy/default.conf:/etc/nginx/sites-available/default
    api:
        build:
          context: ./node_graphQL_server_with_prisma
        depends_on:
          - db
        restart: always
    nginx:
        build:
            context: ./nginx
        volumes:
          - ./nginx/templates:/etc/nginx/templates
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        ports:
          - "5002:80"
        depends_on:
          - api
          - frontend
volumes:
    pg-datafolderv8:
    